### ISSUE TITLE
Errors in Running Fsee Examples

### ISSUE THREAD

**Issue by fadlisa** [strawlab/fsee#1]
I am attempting to implement the fmech, fsee and Drosophila eye map components of the GUF model the latter of which was re-released last year.

I was able to complete the installation successfully however I ran into problems when I attempted to try some examples in the fsee examples folder:

Running **simple.py** gives me the following error:

File "/usr/local/lib/python2.7/dist-packages/fsee-0.2-py2.7-linux-x86_64.egg/fsee/eye_geometry/precomputed_synthetic.py", line 13, in <module>
    receptor_weight_matrix_64 = scipy.io.loadmat(open(os.path.join(datadir,"receptor_weight_matrix_64_synthetic.mat"),mode="rb"))["receptor_weight_matrix_64"]

Running **situated_fly.py** gives me the following error:
fsee: EMDsim.py: IMPORTANT: using photoreceptor temporal dynamics values for Drosophila fit to Juusola & Hardie, 2001
/usr/local/lib/python2.7/dist-packages/fsee-0.2-py2.7-linux-x86_64.egg/fsee/EMDSim.py:94: RuntimeWarning: divide by zero encountered in log
  return K*nx.exp(-(nx.log(t/tp)**2)/(2*sigma**2))
fsee: EMDsim.py: Not using EMDSim.py's quick luminance adaptation
fsee: EMDsim.py: making EMD lowpass filter: tau ~35 msec
situated_fly.py:78: UserWarning: view direciton wrong
  warnings.warn('view direciton wrong')
memory leak in fsoi_ng.cpp, line 642
memory leak for node in fsoi_ng.cpp, line 674

Running **expanding_wall.py** gives me the following error:
fsee: EMDsim.py: IMPORTANT: using photoreceptor temporal dynamics values for Drosophila fit to Juusola & Hardie, 2001
/usr/local/lib/python2.7/dist-packages/fsee-0.2-py2.7-linux-x86_64.egg/fsee/EMDSim.py:94: RuntimeWarning: divide by zero encountered in log
  return K*nx.exp(-(nx.log(t/tp)**2)/(2*sigma**2))
fsee: EMDsim.py: Not using EMDSim.py's quick luminance adaptation
fsee: EMDsim.py: making EMD lowpass filter: tau ~35 msec
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:1288: UserWarning: findfont: Font family [u'sans-serif'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))

On running expanding_wall.py, a window does appear for a few seconds (see attachment below) but then disappears.

![screenshot from 2018-01-22 18-59-31](https://user-images.githubusercontent.com/21019539/35347501-36a37c96-012d-11e8-8393-7433b453bb72.png)

**Comment by astraw** [comment]
Thanks for the report.

I fixed a few bugs that I think you were hitting and updated the README to indicate how to build the precomputed geometry files (namely go into `fsee/eye_geometry` and run `make`).

In the future, please check if your errors are complete and open a separate issue for each one. For example, the first one with `simple.py` does not actually list an error. When running it myself, I could see indeed there was a problem. With the other two and the fixes I just made, I am not running into any problems. Some of the examples save files -- check if you have new files that were just generated after running the examples. With those two examples, I do indeed get seemingly correct newly generated image files.

I think this is fixed now, but please re-open or file new issues if not.

**Comment by astraw** [comment]
Oh, and the image window with the colored squares is because when I wrote this I couldn't figure out how to open an offscreen buffer, and so I just drew something very simple on the screen. This is expected. (A texture that says something like "fsee running... please wait" would have been more helpful.)

**Comment by fadlisa** [comment]
Thank you for your responses and for the feedback. I'll let you know if I have any issues.
